# Generated by Django 5.0.6 on 2024-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.CharField(choices=[('<12', 'Less than 12'), ('12<18', '12 to 17'), ('>18', 'Over 18')], default='', max_length=5)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=10)),
                ('Phone', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=100)),
                ('Date', models.DateField(default='')),
                ('Time', models.TimeField(default='')),
                ('Address1', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(blank=True, default='', max_length=100)),
                ('City', models.CharField(default='', max_length=50)),
                ('Area', models.CharField(blank=True, default='', max_length=50)),
                ('District', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Pincode', models.CharField(default='', max_length=10)),
                ('Nationality', models.CharField(default='', max_length=50)),
                ('Count', models.IntegerField(default='')),
                ('Request', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
