# Generated by Django 5.0.6 on 2024-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0002_alter_book_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='book',
            name='City',
        ),
        migrations.RemoveField(
            model_name='book',
            name='District',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Nationality',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='book',
            name='State',
        ),
    ]
