# Generated by Django 5.0.6 on 2024-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0003_remove_book_address2_remove_book_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='desserts/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
