# Generated by Django 5.0.6 on 2024-08-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0006_mocktails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mocktails',
            new_name='Mocktail',
        ),
    ]
