# Generated by Django 5.0.6 on 2024-08-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dessert',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
