# Generated by Django 5.0.6 on 2024-08-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0012_remove_cartitem_cart_remove_cartitem_dessert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='indian/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
