# Generated by Django 5.0.6 on 2024-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0014_indiancuisine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndianCuisine',
        ),
    ]
