# Generated by Django 5.0.6 on 2024-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YumYum', '0016_chinese'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Table',
            field=models.IntegerField(default=1),
        ),
    ]
